version: '2'
services:
    monappeloffre-app:
        image: monappeloffre
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monappeloffre-mysql:3306/monappeloffre?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monappeloffre-mysql:
        extends:
            file: mysql.yml
            service: monappeloffre-mysql
